version: '3.8'

services:
  demo-app:
    build:
      context: .   # Path where your Dockerfile is located
      dockerfile: Dockerfile
    container_name: demo-app-container
    ports:
      - "8080:8080"
    restart: always
